### ISSUE TITLE
설치 시, 오류 발생과 함께 theme 적용이 정상적으로 되지 않는 문제 발생

### ISSUE THREAD

**Issue by imironjin** [mulder21c/hexo-theme-amorfati-v2#290]
### 체크리스트

- [X] 노드 16.16.0 이상 버전 사용 중
- [X] 현재 [issues](https://github.com/mulder21c/hexo-theme-carpediem/issues)를 검색해보았지만 도움을 얻을 수 없었다.

### 재현 절차

```
npm install hexo-cli -g
hexo init <폴더명>
cd <폴더명>
npm install
```

```
$ cd <폴더명>
$ git clone -b main --single-branch --depth=1 https://github.com/mulder21c/hexo-theme-carpediem.git themes/carpediem
```
```
$ cd themes/carpediem
$ npm install
```

```
$ cd ../..
$ npm install
```

### 기대했던 동작

정상적인 theme 적용을 기대했습니다.

### 실제 동작

theme이 정상적으로 적용되지 않았고, 해당 첨부파일과 같은 형태로 보이게 됩니다. 

### 스크린샷

# 설치 시에 나타나는 오류
![image](https://github.com/mulder21c/hexo-theme-carpediem/assets/94541099/6e4cb6dc-61a6-4afe-b830-8801201d675d)

# 정상적으로 화면이 보이지 않음
![image](https://github.com/mulder21c/hexo-theme-carpediem/assets/94541099/286ce5fe-52a7-4f8d-b013-1d62131a93db)
---
![image](https://github.com/mulder21c/hexo-theme-carpediem/assets/94541099/d22d7f5c-cbef-47be-b2de-84c0e5e1d682)

### node & npm 버전

```Text
$ node -v
v18.12.1

$ npm -v
8.19.2
```

### 기기 정보

기기: `노트북`
OS: `window11`
브라우저: `chrome`
브라우저 버전: `116.0.5845.111(공식 빌드) (64비트)`

**Comment by mulder21c** [comment]
@imironjin 안녕하세요
제가 테스트 중에 `_config.yml`에 algolia를 설정했던 걸 릴리즈에서 미처 빼지 않아 발생한 문제로 보입니다.

`theme/carpediem/_config.yml`에서 

```js
search: algolia
```
를 
```js
search: 
```
로 수정 후 설치를 시도해보시면 해결됩니다 

해당 문제는 패치해 두도록 하겠습니다. 
감사합니다 😅

혹시 문제가 다시 발생하면 추가로 댓글 주세요~

**Comment by imironjin** [comment]
@mulder21c 안녕하세요. 먼저 빠른 답변 감사합니다☺️
해당 `_config.yml` 부분만 수정 후 설치를 진행하고 다시 `$ hexo server` 를 통해 확인을 해보았는데 첨부한 사진과 같이 블로그 테마가 깨지는 현상이 나타나는데 설치 과정에서 누락된 부분이 있는걸까요 ?

![image](https://github.com/mulder21c/hexo-theme-carpediem/assets/94541099/b0e44d92-ce9f-44a6-b00b-a883ef804ace)

![image](https://github.com/mulder21c/hexo-theme-carpediem/assets/94541099/11b09322-705a-4754-a885-9aebd017b0d2)

**Comment by mulder21c** [comment]
@imironjin 
혹
```bash
$ hexo clean
```

후에 

```bash
$ hexo server
```

를 다시 시도해보시겠어요?

앞서 깨진 것이 남아서 생긴 문제 같습니다 ^^;;

**Comment by imironjin** [comment]
@mulder21c
해당 명령어로 clean 후에도 동일하게 레이아웃이 깨지는 현상이 발생합니다.
설치 과정에서는 큰 문제 없이 설치되는듯 보이는데 어떤 부분이 문제인지 잘모르겠네요.. 다른 브라우저에서도 동일합니다. 😥

**Comment by mulder21c** [comment]
@imironjin 
엄... node, npm 버전을 맞춰놓고 다시 테스트 해봐도 제 쪽에서는 문제 없이 구동 되고 있거든요

첨부해주신 스크린샷 기준으로는 pug는 정상으로 렌더링이 완료되었고 css가 반영되지 않은 것으로 보이는데

테스트를 위해 다음 항목들을 확인 부탁드립니다.

1. 현재 쉘을 구동하는 환경이 어떻게 되나요?
2. hexo generate 이후 `public/css/index.css` 가 생성되는지 확인해주시고 생성되었다면 파일을 보내봐 주시겠어요? (여기에 등록해주셔도 되고, gist 등을 이용해서 링크를 주셔도 좋습니다)
3. hexo의 _config.yml과 theme의 _config.yml도 첨부해주시면 한 번에 테스트 해 볼 수 있을 것 같습니다

위 와 별개로 환경에 따라 패키지 설치 버전의 차이일 수 있으니 theme/carpediem의  node_modules 디렉토리를 제거하고 [package-lock.txt](https://github.com/mulder21c/hexo-theme-carpediem/files/12440653/package-lock.txt) 파일을 package-lock.json으로 저장하셔서 기존 것을 교체한 후 패키지 설치를 다시 시도해보시겠어요?

**Comment by imironjin** [comment]
@mulder21c
1. bash 쉘입니다
2. https://gist.github.com/imironjin/9243bfff13001c6a1b383dd4804b2d8a
css파일, _config.yml 파일 2개 함께 첨부하였습니다. config.yml 파일 이름 중복으로 인하여 -hexo, -theme 붙여서 첨부하였습니다.

**Comment by mulder21c** [comment]
@imironjin windows에서 구동하는 bash 쉘인가요? 아니면 리눅스 bash 인가요?

**Comment by imironjin** [comment]
@mulder21c 쉘은 Git Bash로 Windows 환경에서 실행 중입니다.

**Comment by mulder21c** [comment]
@imironjin Windows 환경에서 문제가 발생하는 것으로 확인했고, 경로를 찾아주는 특정 패키지가 windows에서 정상적으로 작동이 되지 않고 있네요 ;;;
다소 해당 문제를 해결하려면 현재 일정 상 다소 시간이 걸릴 듯 해서 미리 말씀 드립니다.
(제가 윈도우를 너무 버려놨네요 ;;;; 😭😭)

**Comment by imironjin** [comment]
@mulder21c 앗..그랬군요. 답변 감사합니다 ! 🥹

**Comment by mulder21c** [comment]
@imironjin 안녕하세요
해당 문제를 해결하여 릴리즈 해두었습니다.
덕분에 놓치고 있던 Windows에서의 문제를 수정할 수 있었네요 😅
최신 상태로 업데이트 후에 다시 시도해보시면 스타일이 정상으로 뜨는 걸 확인하실 수 있습니다~~
불편을 드려 죄송하고 기다리시게 되어 죄송합니다 😭😭

Windows 11(Sandbox) + Git Bash + Node@latest 에서 정상으로 돌아가는 것까지 확인하고 릴리즈 해두었는데
혹시라도 추가로 문제가 발생한다면 언제든 이슈 올려주세요~

감사합니다 👍

**Comment by imironjin** [comment]
@mulder21c 
정상 작동 확인하였습니다. 감사합니다 🥹
